---

- include: ip-list.yml
  tags:
    - always

- include: apt_prepare.yml
  when: ansible_pkg_mgr == 'apt'
  tags:
   - debian
   - install

- include: rpm_prepare.yml
  when: ansible_os_family == 'RedHat'
  tags:
   - centos
   - fedora
   - install

- include: openbsd_prepare.yml
  when: ansible_system == 'OpenBSD'
  tags:
   - openbsd

- include: freebsd_prepare.yml
  when: ansible_system == 'FreeBSD'
  tags:
   - freebsd

# we specifically opt for present over latest to improve performance
- name: Ensure tor is installed
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ tor_packages }}"
  # apt starts a tor client instance by default after installing the package
  # we do not need that
  notify:
    - stop-and-mask default tor instance
    - disable default tor instance FreeBSD
  tags:
   - openbsd
   - freebsd
   - debian
   - centos
   - fedora
   - install

- meta: flush_handlers

- include: configure.yml
  tags:
   - debian
   - centos
   - fedora
   - openbsd
   - freebsd

- include: linux_service.yml
  when: ansible_system == 'Linux'
  tags:
   - debian
   - centos
   - fedora

- include: openbsd_service.yml
  when: ansible_system == 'OpenBSD'
  tags:
   - openbsd

- include: freebsd_service.yml
  when: ansible_system == 'FreeBSD'
  tags:
   - freebsd
