---
- name: stop-and-mask default tor instance
  become: yes
  shell: systemctl stop tor@default && systemctl mask tor@default
  when: ansible_pkg_mgr == 'apt'

- name: restart apparmor
  become: yes
  service: name=apparmor state=restarted

- name: systemctl daemon-reload
  become: yes
  command: systemctl daemon-reload

- name: re-gather facts
  setup:
  when: ansible_pkg_mgr == 'dnf'

- name: disable default tor instance FreeBSD
  become: yes
  lineinfile:
    dest: /etc/rc.conf
    line: "tor_disable_default_instance=\"YES\""
    create: yes
  when: ansible_system == 'FreeBSD'

# TODO: this reloads all instances on a FreeBSD host even if just one torrc changed
- name: Ensure Tor instances are reloaded if its torrc changed (FreeBSD)
  become: yes
  service:
    name: tor
    state: reloaded
  when: ansible_system == 'FreeBSD'
